# Generated by Django 6.0 on 2025-12-28 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal')], max_length=20)),
                ('sensitive', models.BooleanField(default=False)),
                ('acne_prone', models.BooleanField(default=False)),
                ('age_range', models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18–24'), ('25_34', '25–34'), ('35_44', '35–44'), ('45_plus', '45+')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other / Prefer not to say')], max_length=20, null=True)),
                ('assessment_data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
