# Generated by Django 6.0 on 2025-12-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='assessment_data',
            field=models.JSONField(default=dict),
        ),
    ]
